import { AdminPHColumnType, PHColumnType } from '../components/PrintHistory/PHColumnType';

export const printHistoryData: PHColumnType[] = [
  {
    id: 1,
    documentName: 'Annual Report 2024',
    printingState: 'success',
    printingTime: new Date('2024-11-01T10:30:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Duplex',
  },
  {
    id: 2,
    documentName: 'Invoice #1023',
    printingState: 'fail',
    printingTime: new Date('2024-11-03T15:15:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Single-sided',
  },
  {
    id: 3,
    documentName: 'Project Proposal',
    printingState: 'success',
    printingTime: new Date('2024-11-05T09:45:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Single-sided',
  },
  {
    id: 4,
    documentName: 'Meeting Agenda',
    printingState: 'fail',
    printingTime: new Date('2024-11-02T08:20:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Duplex',
  },
  {
    id: 5,
    documentName: 'Training Manual',
    printingState: 'success',
    printingTime: new Date('2024-11-06T14:10:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Stapled',
  },
  {
    id: 6,
    documentName: 'Monthly Budget Review',
    printingState: 'success',
    printingTime: new Date('2024-11-07T11:30:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Duplex',
  },
  {
    id: 7,
    documentName: 'Employee Handbook',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T13:50:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Single-sided',
  },
  {
    id: 8,
    documentName: 'Conference Brochure',
    printingState: 'success',
    printingTime: new Date('2024-11-06T10:05:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Stapled',
  },
  {
    id: 9,
    documentName: 'Audit Summary',
    printingState: 'fail',
    printingTime: new Date('2024-11-01T09:40:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Duplex',
  },
  {
    id: 10,
    documentName: 'Sales Report Q4',
    printingState: 'success',
    printingTime: new Date('2024-11-05T16:20:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Single-sided',
  },
  {
    id: 11,
    documentName: 'Marketing Plan 2025',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T17:30:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Duplex',
  },
  {
    id: 12,
    documentName: 'IT Infrastructure Update',
    printingState: 'success',
    printingTime: new Date('2024-11-07T08:50:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Stapled',
  },
  {
    id: 13,
    documentName: 'Legal Agreement',
    printingState: 'success',
    printingTime: new Date('2024-11-05T13:15:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Single-sided',
  },
  {
    id: 14,
    documentName: 'HR Policy Guide',
    printingState: 'fail',
    printingTime: new Date('2024-11-02T15:00:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Duplex',
  },
  {
    id: 15,
    documentName: 'Client Presentation',
    printingState: 'success',
    printingTime: new Date('2024-11-03T09:25:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Stapled',
  },
  {
    id: 16,
    documentName: 'Meeting Minutes',
    printingState: 'success',
    printingTime: new Date('2024-11-07T15:45:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Single-sided',
  },
  {
    id: 17,
    documentName: 'Technical Manual',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T12:35:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Duplex',
  },
  {
    id: 18,
    documentName: 'Newsletter November',
    printingState: 'success',
    printingTime: new Date('2024-11-06T14:50:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Single-sided',
  },
  {
    id: 19,
    documentName: 'Expense Report October',
    printingState: 'fail',
    printingTime: new Date('2024-11-05T07:55:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Stapled',
  },
  {
    id: 20,
    documentName: 'Project Roadmap',
    printingState: 'success',
    printingTime: new Date('2024-11-02T16:40:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Duplex',
  },
  {
    id: 21,
    documentName: 'Press Release',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T11:10:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Single-sided',
  },
  {
    id: 22,
    documentName: 'Annual Budget Forecast',
    printingState: 'success',
    printingTime: new Date('2024-11-06T09:30:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Duplex',
  },
  {
    id: 23,
    documentName: 'Policy Update Memo',
    printingState: 'success',
    printingTime: new Date('2024-11-07T13:05:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Black & White, Single-sided',
  },
  {
    id: 24,
    documentName: 'Supplier Contract',
    printingState: 'fail',
    printingTime: new Date('2024-11-03T11:35:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Stapled',
  },
  {
    id: 25,
    documentName: 'Supplier Contract',
    printingState: 'fail',
    printingTime: new Date('2024-11-03T11:35:00Z'),
    printerName: '206B1Toshiba',
    properties: 'Color, Stapled',
  },
];

export const adminPrintHistoryData: AdminPHColumnType[] = [
  {
    id: 1,
    documentName: 'Annual Report 2024',
    printingState: 'success',
    printingTime: new Date('2024-11-01T10:30:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 2,
    documentName: 'Invoice #1023',
    printingState: 'fail',
    printingTime: new Date('2024-11-03T15:15:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 3,
    documentName: 'Project Proposal',
    printingState: 'success',
    printingTime: new Date('2024-11-05T09:45:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 4,
    documentName: 'Meeting Agenda',
    printingState: 'fail',
    printingTime: new Date('2024-11-02T08:20:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 5,
    documentName: 'Training Manual',
    printingState: 'success',
    printingTime: new Date('2024-11-06T14:10:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 6,
    documentName: 'Monthly Budget Review',
    printingState: 'success',
    printingTime: new Date('2024-11-07T11:30:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 7,
    documentName: 'Employee Handbook',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T13:50:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 8,
    documentName: 'Conference Brochure',
    printingState: 'success',
    printingTime: new Date('2024-11-06T10:05:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 9,
    documentName: 'Audit Summary',
    printingState: 'fail',
    printingTime: new Date('2024-11-01T09:40:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 10,
    documentName: 'Sales Report Q4',
    printingState: 'success',
    printingTime: new Date('2024-11-05T16:20:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 11,
    documentName: 'Marketing Plan 2025',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T17:30:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 12,
    documentName: 'IT Infrastructure Update',
    printingState: 'success',
    printingTime: new Date('2024-11-07T08:50:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 13,
    documentName: 'Legal Agreement',
    printingState: 'success',
    printingTime: new Date('2024-11-05T13:15:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 14,
    documentName: 'HR Policy Guide',
    printingState: 'fail',
    printingTime: new Date('2024-11-02T15:00:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 15,
    documentName: 'Client Presentation',
    printingState: 'success',
    printingTime: new Date('2024-11-03T09:25:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 16,
    documentName: 'Meeting Minutes',
    printingState: 'success',
    printingTime: new Date('2024-11-07T15:45:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 17,
    documentName: 'Technical Manual',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T12:35:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 18,
    documentName: 'Newsletter November',
    printingState: 'success',
    printingTime: new Date('2024-11-06T14:50:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 19,
    documentName: 'Expense Report October',
    printingState: 'fail',
    printingTime: new Date('2024-11-05T07:55:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 20,
    documentName: 'Project Roadmap',
    printingState: 'success',
    printingTime: new Date('2024-11-02T16:40:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 21,
    documentName: 'Press Release',
    printingState: 'fail',
    printingTime: new Date('2024-11-04T11:10:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 22,
    documentName: 'Annual Budget Forecast',
    printingState: 'success',
    printingTime: new Date('2024-11-06T09:30:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 23,
    documentName: 'Policy Update Memo',
    printingState: 'success',
    printingTime: new Date('2024-11-07T13:05:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 24,
    documentName: 'Supplier Contract',
    printingState: 'fail',
    printingTime: new Date('2024-11-03T11:35:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
  {
    id: 25,
    documentName: 'Supplier Contract',
    printingState: 'fail',
    printingTime: new Date('2024-11-03T11:35:00Z'),
    printerName: '206B1Toshiba',
    username: 'Phan Quoc Khai',
  },
];
