import { PrinterListColumnType } from '../components/PrinterList/PrinterListColumn';

export const printerListData: PrinterListColumnType[] = [
  {
    id: 1,
    printerName: 'HP LaserJet Pro M404dn',
    printerBrand: 'HP',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: true,
  },
  {
    id: 2,
    printerName: 'Canon PIXMA G7070',
    printerBrand: 'Canon',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: true,
  },
  {
    id: 3,
    printerName: 'Epson EcoTank L3250',
    printerBrand: 'Epson',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: false,
  },
  {
    id: 4,
    printerName: 'HP Color LaserJet Pro MFP',
    printerBrand: 'HP',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: true,
  },
  {
    id: 5,
    printerName: 'Canon imageCLASS MF244dw',
    printerBrand: 'Canon',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: true,
  },
  {
    id: 6,
    printerName: 'Epson WorkForce WF-2850',
    printerBrand: 'Epson',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: false,
  },
  {
    id: 7,
    printerName: 'HP OfficeJet Pro 9015',
    printerBrand: 'HP',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: true,
  },
  {
    id: 8,
    printerName: 'Canon MAXIFY GX7070',
    printerBrand: 'Canon',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: true,
  },
  {
    id: 9,
    printerName: 'Epson Expression ET-2850',
    printerBrand: 'Epson',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: false,
  },
  {
    id: 10,
    printerName: 'HP LaserJet Enterprise M507',
    printerBrand: 'HP',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: true,
  },
  {
    id: 11,
    printerName: 'Canon i-SENSYS MF645Cx',
    printerBrand: 'Canon',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: true,
  },
  {
    id: 12,
    printerName: 'Epson SureColor P700',
    printerBrand: 'Epson',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: true,
  },
  {
    id: 13,
    printerName: 'HP PageWide Pro 477dw',
    printerBrand: 'HP',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: false,
  },
  {
    id: 14,
    printerName: 'Canon PIXMA TR8670',
    printerBrand: 'Canon',
    printerLocation: 'B6-102',
    printerBK: 'BKTD',
    active: true,
  },
  {
    id: 15,
    printerName: 'Epson EcoTank L6490',
    printerBrand: 'Epson',
    printerLocation: 'B6-102',
    printerBK: 'BKLTK',
    active: true,
  },
];
